### ISSUE TITLE
Docker image缺失文件

### ISSUE THREAD

**Issue by 0akarma** [jacktao007/dss-docker-compose#1]
1.0.x单容器(推荐) 链接: https://pan.baidu.com/s/1Fk-XPVPU7fvhwwFJhrbHSA 提取码: 9pvb
能提供下文件hash吗，下载后load不进去。
```
open /var/lib/docker/tmp/docker-import-826058842/appcom/json: no such file or directory
```

**Comment by jacktao007** [comment]
确保硬盘有足够的空闲空间  10G以上

**Comment by 0akarma** [comment]
可以了，谢谢，我一开始没用`docker import`，用的`docker load`

**Comment by 0akarma** [comment]
期待大佬适配好1.1.x的docker-compose版本:D

**Comment by jacktao007** [comment]
https://linkis.incubator.apache.org/blog/2022/07/16/deploy-linkis-with-kubernetes  已经有了 尝试 dev-1.3.0分支

**Comment by 0akarma** [comment]
> https://linkis.incubator.apache.org/blog/2022/07/16/deploy-linkis-with-kubernetes 已经有了 尝试 dev-1.3.0分支

dss的dev-1.3.0？貌似现在只有1.2.0

**Comment by jacktao007** [comment]
1.3.0 版本发布就有了
